# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^analyses|^poetry\.lock$
repos:
- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.15
  hooks:
  - id: validate-pyproject
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-merge-conflict
  - id: check-toml
  - id: check-json
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: forbid-submodules
  - id: trailing-whitespace
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.11.0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.7.1
  hooks:
  - id: mypy
    args:
    - --install-types
    - --non-interactive
- repo: https://github.com/commitizen-tools/commitizen
  hooks:
  - id: commitizen
  rev: 3.12.0
- repo: https://github.com/PyCQA/autoflake
  rev: v2.2.1
  hooks:
  - id: autoflake
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-toml
    args:
    - --autofix
  - id: pretty-format-yaml
    args:
    - --autofix
