# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: ^poetry\.lock$
repos:
- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.15
  hooks:
  - id: validate-pyproject
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.4
  hooks:
  - id: forbid-crlf
  - id: remove-crlf
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: forbid-submodules
  - id: trailing-whitespace
# autoflake before black and isort
# to avoid having to run pre-commit twice
- repo: https://github.com/PyCQA/autoflake
  rev: v2.2.1
  hooks:
  - id: autoflake
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.10.1
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
- repo: https://github.com/commitizen-tools/commitizen
  hooks:
  - id: commitizen
  rev: 3.12.0
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
  - id: pyupgrade
    args:
    - --py38-plus  # Adjust this for the highest version your project needs.
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-toml
    args:
    - --autofix
  - id: pretty-format-yaml
    args:
    - --autofix
