[tool.autoflake]
expand-star-imports = true
recursive = true
remove-all-unused-imports = true
remove-duplicate-keys = true
remove-unused-variables = true

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.mypy]
check_untyped_defs = true
files = ["."]
ignore_missing_imports = true

[tool.poetry]
authors = ["Ben Jeffrey <bjeffrey92@hotmail.com>"]
description = "FPL Predictor"
name = "fpl_predictor"
packages = [
  {include = "fpl_predictor"}
]
version = "0.0.0"

[tool.poetry.dependencies]
jmespath = "^1.0.1"
polars = "^0.19.16"
python = "3.11.*"
requests = "^2.31.0"
scikit-learn = "^1.3.2"
scipy = "^1.11.4"

[tool.poetry.group.dev.dependencies]
black = "^23.12.1"
isort = "^5.13.1"
mypy = "^1.5.1"
pre-commit = "^3.4.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.4"
pytest-cov = "^4.1.0"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
